version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      VENDOR: 'xiaomi'
      CODENAME: 'jasmine_sprout'
      MAINTAINER: '@AndroiableDroid'
      FLAVOR: 'eng'
      # Remove the following when Publishing Official
      # TEST_BUILD: 'true'
      # Only for Official Build, uncomment following
      PB_OFFICIAL: 'true'
      CHANGELOG: " - Bringup 3.0\n
          - Source side changes\n
          - Fully Redesigned UI\n
	  - New Android like Power Menu (Activated via power key hold)\n
	  - Flashlight toggled by Vol up(+) on hold\n
	  - Flashlight toggle on Lockscreen\n
	  - Stock Android 10 ROM Decryption (password needed)\n
          - Etc."
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
