version: 2
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/pitchblack-builder:latest
    working_directory: /home/builder/pitchblack
    steps:
      - checkout
      - run:
          name: Set Project ENV Variables
          command: |
            echo "export MANIFEST_BRANCH='android-9.0'" >> $BASH_ENV
            echo "export PBRP_BRANCH='android-9.0'" >> $BASH_ENV
            echo "export BRANCH='features'" >> $BASH_ENV
            echo "export VERSION='2.9.0'" >> $BASH_ENV
            echo "export VENDOR='xiaomi'" >> $BASH_ENV
            echo "export CODENAME='jasmine_sprout'" >> $BASH_ENV
            echo "export BUILD_LUNCH='omni_jasmine_sprout-userdebug'" >> $BASH_ENV
      - run:
          name: AIO Build
          command: |
            echo "Initializing"
            echo -en "The Whole PATH ENV is - " && echo $PATH
            which ghr && which repo
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            echo "Initialize & Sync PBRP repo"
            echo $(pwd)
            repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth 1
            time repo sync -c -f -q --force-sync --no-clone-bundle --no-tags -j32
            echo "Clean up the .repo, no use of it"
            cp -a .repo/manifests $(pwd)/ && ls manifests/
            rm -rf .repo
            mkdir -p .repo && mv manifests .repo/ && ls -la .repo/*
            echo "Source Files are Here now"
            ls -la .
            echo "Get the Device Tree on place"
            git clone https://$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/${CIRCLE_PROJECT_REPONAME} device/${VENDOR}/${CODENAME}
            rm -rf bootable/recovery && git clone https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b ${BRANCH} bootable/recovery
            rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb vendor/pb
            echo "Start the Build Process"
            export ALLOW_MISSING_DEPENDENCIES=true
            source build/envsetup.sh
            lunch ${BUILD_LUNCH}
            make -j16 recoveryimage
            echo "Deploying"
            sudo chmod a+x vendor/pb/pb_deploy.sh && ./vendor/pb/pb_deploy.sh ${CODENAME} ${SFUserName} ${SFPassword} ${GITHUB_TOKEN}
            export BUILDFILE=$(find $(pwd)/out/target/product/${CODENAME}/PitchBlack*.zip 2>/dev/null)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ${BUILDFILE}
      - store_artifacts:
          path: out/target/product/${CODENAME}/PitchBlack*.zip
      - store_artifacts:
          path: out/target/product/${CODENAME}/recovery.img
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - pb
